### PR TITLE
Update ReadMe.md

### PR DESCRIPTION
**Pull request by forestgeoadm**
Hi @biancaglez, cool stuff!  It's neat how you were able to merge two data sets to provide annual data for a longer period.  I made a few minor edits, and I have a few questions:

- [x] 1.  What does CRU mean?  I've seen it elsewhere on the site and imagine that it's Climate Repo ...something.

**BG**  _updated the definition in the read me and linked to it-- let me know if that works!_ 

- [x] 2.  Will the Moana Loa data automatically update within your script, or should we clarify that the data is current through 2019?

**BG**  _Clarified in readme_

- [x] 3.  The last bullet point of your "Data sources" section is a link to the data - is that equivalently citing your sources, or would researchers need to interface with that data externally before they could use your script?

**BG:** _This last bullet point is the way that researchers can download a fresh batch of data. So both citing my source and pointing them to the location where they can find it_  

- [x] 4.  For Moana Loa's "Variables used" section you used the general categories of value and year, defining them in the next section, "Variable definitions," but in the NOAA section you supplied more information in the "Variables used" section and then basically repeated it in the "Variable definitions" section.  Perhaps the "Variables used" for both NOAA and Moana Loa could be "time" and "CO2 value" and then differentiated in the "Variables defined" section?

**BG:** _I prefer to leave them as they are, because these are the actual names of the variables in the dataset (there are probably about 20 of them so I want someone to be able to easily pick them out of the dataset if they have to use them_

- [x] FYI the links to the READMEs led me to 404 pages.  

**BG:** _Great, thanks for the heads up. I think Krista rearranged files and the links broke. They should be up and running again, but let me know if they aren't_

Take care, 
Caly (the human behind @forestgeo/adm )

### CODE REVIEW

**Comment by teixeirak** [comment]
Thanks @forestgeo/adm ! I approved the pull request and will leave it to @biancaglez  to respond on your questions.

A typo: It should be M*au*na Loa, not M*oa*na Loa.

**Comment by biancaglez** [comment]
@forestgeo/adm 

Hey, Caly! 

Thanks for the suggestions above ^^ so good to have another eye looking at my work. I appreciate the suggestions. I've made some edits to your comments above. Let me know if all of your suggestions have been implemented or if my alternative works.

Thanks for your time.
Bianca

**Comment by teixeirak** [comment]
@forestgeo/adm , @biancaglez , thanks for the progress on this! On Friday, I approved but forgot to actually merge Caly's suggested changes, which resulted in a conflicted copy. I just went through and did my best to resolve differences, but it would be good to check that your desired changes went through.

**Comment by forestgeoadm** [comment]
Hi, @biancaglez - thanks for your thorough answers to my questions!  Between your responses and @teixeirak's edits I think everything was addressed.  A few new observations/questions:

1.  It took me a few minutes to realize that READMEs would be in files that data users access by clicking "View raw" from the link that we currently direct them towards.  I had expected a page like the README for CO2 data.  This may very well be me being a data novice, but perhaps it would be helpful to add an MD file with just the introductory text of the READMEs?  I think it could also be valuable to clarify if we authored those READMEs or if NOAA/Mauna Loa did (I think the latter is true?).

2.  It's clear that the current data set spans from 1901-2019 AND that more current data is available.  If data users want to update the data set would they do that by using the script that you made, Bianca?  Again, probably me being a data novice, but it's not clear to me if sharing the script a) shows people your method for combining the data sets, b) empowers people to update the combined data set over time, or c) both a &b.

3.  Krista, wit regards to citation - do we simply want to provide citation for the original data sets, or do we want to acknowledge the Climate Data Portal for curating/cleaning/combining data?

Take care,
Caly

**Comment by teixeirak** [comment]
>     3\. Krista, wit regards to citation - do we simply want to provide citation for the original data sets, or do we want to acknowledge the Climate Data Portal for curating/cleaning/combining data?

Good question.  It would be kind of nice to draw attention to the fact that the resource exists, but I don't really feel that it's necessary to cite the ForestGEO Climate Data Portal for this. (It's not like it would be all that difficult for other groups to reproduce this analysis!) I guess that if they get the data from there, they should cite it for the sake of transparency/ reproducibility, but I certainly wouldn't feel slighted if someone skipped that citation. 

By the way, we can get a stable DOI to the whole repo, which people could cite. When we feel we have a good version 1.0, I'll get us a DOI.

**Comment by forestgeoadm** [comment]
Hi @teixeirak, thanks for this!

I agree with you that for transparency we should add some acknowledgement that the data were organized and made accessible by another party.  

Another piece to consider is the original data creator's Data Use policy.  An excerpt of Mauna Loa's reads, "If the data are obtained for potential use in a publication or presentation, ESRL should be informed at the outset of the nature of this work.  If the ESRL data are essential to the work, or if an important result or conclusion depends on the ESRL data, co-authorship may be appropriate."  This seems like an important instruction to pass on clearly.

I'll keep thinking about the specific forms that these considerations should take. 

Take care,
Caly

**Pull request merged**
