### PR TITLE
Drafted README

### PR DESCRIPTION
**Pull request by forestgeoadm**
Hi @biancaglez,

Here's what I've put together as a draft of a README.  I've bolded and bracketed pieces where I have outstanding questions.

I sense that you wanted to include more information about your methods/direct people to [this page](https://github.com/sbegueria/SPEI) for more info, but, to be honest, I don't understand the process well enough to relay how all of the pieces fit together, so some aren't here.  I'm happy to keep adding/amending this page, so just let me know what next steps should be.

Take care,
Caly

### CODE REVIEW

**Comment by forestgeoadm** [comment]
Hi, @biancaglez - I'm glad that you thought the draft was good enough to share.  How shall we address the bracketed questions re: # of ForestGEO sites and SPEIbase.github.Rproj?

Take care,
Caly

**Comment by biancaglez** [comment]
Woops, sorry Caly! I thought I had to merge it to view. But yes, I have a few things to fix on my end (e.g, the site numbers). I can also delete the .Rproj, as it's unnecessary now.

**Comment by forestgeoadm** [comment]
Sounds good, @biancaglez - if I can be of any help, just give a yell.

**Comment by biancaglez** [comment]
Alrighty @forestgeoadm  - all 69 sites are on there now -- and the project has been deleted. The only difference is instead of a CSV it is a zipped file (.zip) because the file was too large to upload without zipping. Let me know if this works!

**Comment by forestgeoadm** [comment]
Hi, @biancaglez - The file named "spei_all_months.csv" that is in the ForestGEO sites folder has many (presumably all?   I didn't count, just scanned alphabetically) ForestGEO sites, but the file named "spei_all_months.zip" still only has 8 sites.

**Comment by biancaglez** [comment]
Okay check out the superb file organization now https://github.com/forestgeo/Climate/tree/master/Climate_Data/SPEI/data_calculated_with_script

Thanks!

**Comment by forestgeoadm** [comment]
Ha ha - hooray!  Yes, the file organization looks superb :)  I've updated the links so that they're functional, and I've taken out my notes-to-self.  Like I mentioned on Friday, I only included content that I more-or-less understood - so you might want to add a methods section, etc. (which I'm happy to format, I just don't understand it well enough to author it).

**Comment by teixeirak** [comment]
Looks great; thank you both!

**Pull request merged**
